services:
    postgres:
        image: "postgres:15-alpine"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: sudobot
        volumes:
            - pgdata:/var/lib/postgresql/data

    bot:
        build: .
        ports:
            - 4000:4000
        volumes:
            - ./tmp/volume:/data
            - ./tmp/volume/config:/app/config
            - ./tmp/volume/logs:/app/logs
            - ./tmp/volume/storage:/app/storage
            - ./tmp/volume/tmp:/app/tmp
        depends_on:
            - postgres
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    
volumes:
    pgdata:
