site_name: SudoBot Docs

theme: 
  name: 'material'
  custom_dir: docs/overrides
  logo: 'assets/images/sudobot.png'
  favicon:
    'assets/images/sudobot.png'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: 'Roboto'
  
repo_name: 'GitHub'
repo_url: 'https://github.com/virtual-designer/sudobot'
edit_uri: edit/main/docs/

extra_css:
  - 'assets/css/style.css'
  
extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - toc:
        permalink: "#"
  - pymdownx.betterem:
      smart_enable: all

copyright: 'Copyright &copy; OSN Inc. 2022'

