apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudobot
spec:
  selector:
    matchLabels:
      app: sudobot
  template:
    metadata:
      labels:
        app: sudobot
    spec:
      volumes:
        - name: sudobot-pv
          persistentVolumeClaim:
            claimName: sudobot-pvc
      containers:
        - name: sudobot
          volumeMounts:
            - mountPath: /data
              name: sudobot-pv
          stdin: true
          tty: true
          image: ghcr.io/onesoft-sudo/sudobot:latest
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sudobot
                  key: db_password
            - name: DB_URL
              value: postgresql://postgres:$(DB_PASSWORD)@$(POSTGRES_SERVICE_SERVICE_HOST):$(POSTGRES_SERVICE_SERVICE_PORT)/sudobot
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: sudobot
                  key: discord_token
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sudobot
                  key: client_id
            - name: HOME_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: sudobot
                  key: home_guild_id
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sudobot
                  key: jwt_secret
            - name: SUDO_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: SUDO_PREFIX
              value: /data
