# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                node-version: [18.x, 20.x]
                os: [ubuntu-latest, macos-latest]
       
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Libraries (Linux)
              run: sudo apt install build-essential libcurl4 libcurl4-gnutls-dev -y
              if: matrix.os == 'ubuntu-latest'

            - name: Install Libraries and Tools (macOS)
              run: brew install curl
              if: matrix.os == 'macos-latest'

            - name: "Install Native Libraries"
              run: |
                  git clone https://github.com/Cogmasters/concord;
                  cd concord;
                  make;
                  sudo make install;
                  cd ..;

            - name: "Install Dependencies"
              run: npm install

            - name: "Install Dev Dependencies"
              run: npm install -D

            - name: "Generate prisma client"
              run: npx prisma generate

            - name: "ESLint"
              run: npm run lint || echo "ESLint Failed"

            - name: "Build (TypeScript)"
              run: npm run build --if-present

            - name: "Build (Native)"
              run: make

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
