name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: echo "DEBUG=1" > .env.docker

      - name: Set Tag
        run: echo "sudobot:$(date +%s)" > TAG

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $(cat TAG)
          
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u virtual-designer --password-stdin
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Push the Docker image
        run: docker push $(cat TAG)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
