name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: echo "DEBUG=1" > .env.docker

      - name: Build the Docker image
        run: echo "sudobot:$(date +%s)" > TAG && docker build . --file Dockerfile --tag sudobot:$(date +%s)

  publish:
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u virtual-designer --password-stdin

      - name: Push the Docker image
        run: docker push sudobot:$(cat TAG)
