name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        run: echo "DEBUG=1" > .env.docker

      - name: Build the Docker image
        id: build
        run: |
          TAG="sudobot:$(date +%s)";
          docker build . --file Dockerfile --tag $TAG;
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.build.outputs.tag }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u virtual-designer --password-stdin

      - name: Push the Docker image
        run: docker push ${{ needs.build.outputs.tag }}
