# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on: 
  push:
     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.2
      - name: Install Mkdocs
        run: pip install mkdocs mkdocs-material

      - name: Build docs
        run: mkdocs build
        
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          # Git domain (default github.com)
          # Git branch where assets will be deployed
          target_branch: gh-pages
          keep_history: true
          build_dir: site
        
      
        
        
